
-- ============================================================
-- SUSPEND TASKS
-- ============================================================

ALTER TASK IF EXISTS KARTHICKY_DB.PUBLIC.TASK_LOAD_BRONZE SUSPEND;

ALTER TASK IF EXISTS KARTHICKY_DB.PUBLIC.TASK_LOAD_SILVER SUSPEND;

ALTER TASK IF EXISTS KARTHICKY_DB.PUBLIC.TASK_LOAD_GOLD_DIMS SUSPEND;

ALTER TASK IF EXISTS KARTHICKY_DB.PUBLIC.TASK_LOAD_FACT_SALES SUSPEND;
