CREATE OR REPLACE TASK KARTHICKY_DB.PUBLIC.TASK_LOAD_SILVER

WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'

WHEN SYSTEM$STREAM_HAS_DATA(
'KARTHICKY_DB."1_BRONZE".STREAM_BRONZE_TO_SILVER'
)

AS

BEGIN

LET v_batch_id VARCHAR := UUID_STRING();
LET v_rows_processed NUMBER := 0;
LET v_rows_inserted NUMBER := 0;
LET v_rows_updated NUMBER := 0;
LET v_rows_rejected NUMBER := 0;

CREATE OR REPLACE TEMP TABLE KARTHICKY_DB."2_SILVER".STG_BRONZE AS

SELECT *
FROM KARTHICKY_DB."1_BRONZE".STREAM_BRONZE_TO_SILVER;

MERGE INTO KARTHICKY_DB."2_SILVER".PHARMA_SALES_CLEAN tgt

USING (

SELECT *
FROM KARTHICKY_DB."2_SILVER".STG_BRONZE
WHERE _CDC_ACTION = 'DELETE'
   OR (
    TRANSACTION_ID IS NOT NULL
    AND TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY') IS NOT NULL
    AND BRANCH_ID IS NOT NULL
    AND BRANCH_NAME IS NOT NULL AND TRIM(BRANCH_NAME) != ''
    AND DISTRICT IS NOT NULL AND TRIM(DISTRICT) != ''
    AND PROVINCE IS NOT NULL AND TRIM(PROVINCE) != ''
    AND UPPER(PAYMENT_METHOD) IN ('CASH','CARD','INSURANCE')
    AND UPPER(CUSTOMER_GENDER) IN ('MALE','FEMALE')
    AND CUSTOMER_AGE IS NOT NULL AND CUSTOMER_AGE >= 0 AND CUSTOMER_AGE <= 120
    AND CUSTOMER_CITY IS NOT NULL AND TRIM(CUSTOMER_CITY) != ''
    AND MEDICINE_ID IS NOT NULL
    AND MEDICINE_NAME IS NOT NULL AND TRIM(MEDICINE_NAME) != ''
    AND UPPER(DOSAGE_FORM) IN ('TABLET','CAPSULE','SYRUP','DROPS','CREAM','OINTMENT','INHALER','SACHET')
    AND PACK_SIZE IS NOT NULL AND PACK_SIZE > 0
    AND SUPPLIER_NAME IS NOT NULL AND TRIM(SUPPLIER_NAME) != ''
    AND UPPER(PRESCRIPTION_REQUIRED) IN ('YES','NO')
    AND BATCH_NO IS NOT NULL AND TRIM(BATCH_NO) != ''
    AND TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') IS NOT NULL
    AND TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') >= TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY')
    AND QUANTITY IS NOT NULL AND QUANTITY > 0
    AND UNIT_PRICE_LKR IS NOT NULL AND UNIT_PRICE_LKR > 0
    AND DISCOUNT_RATE IS NOT NULL AND DISCOUNT_RATE >= 0 AND DISCOUNT_RATE <= 1
    AND LINE_TOTAL_LKR IS NOT NULL AND LINE_TOTAL_LKR > 0
    AND YEAR IS NOT NULL AND YEAR >= 2000 AND YEAR <= 2100
    AND MONTH IS NOT NULL AND MONTH >= 1 AND MONTH <= 12
   )

) src

ON tgt.TRANSACTION_ID = src.TRANSACTION_ID

WHEN MATCHED
AND src._CDC_ACTION='DELETE'

THEN UPDATE SET

    tgt._IS_SOFT_DELETED = TRUE,
    tgt._LOADED_AT = CURRENT_TIMESTAMP()

WHEN MATCHED
AND tgt._HASH_DIFF != src._HASH_DIFF

THEN UPDATE SET

    tgt.BRANCH_NAME = src.BRANCH_NAME,
    tgt.CUSTOMER_CITY = src.CUSTOMER_CITY,
    tgt.LINE_TOTAL_LKR = src.LINE_TOTAL_LKR,
    tgt._HASH_DIFF = src._HASH_DIFF,
    tgt._LOADED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED
AND src._CDC_ACTION IN ('INSERT','INITIAL_LOAD')

THEN INSERT (

    TRANSACTION_ID,
    TRANSACTION_DATE,

    BRANCH_ID,
    BRANCH_NAME,
    DISTRICT,
    PROVINCE,

    PAYMENT_METHOD,

    CUSTOMER_GENDER,
    CUSTOMER_AGE,
    CUSTOMER_CITY,

    MEDICINE_ID,
    MEDICINE_NAME,
    GENERIC_NAME,
    MEDICINE_CATEGORY,
    DOSAGE_FORM,
    STRENGTH_MG,
    PACK_SIZE,

    SUPPLIER_NAME,

    PRESCRIPTION_REQUIRED,

    BATCH_NO,
    EXPIRY_DATE,

    QUANTITY,
    UNIT_PRICE_LKR,
    DISCOUNT_RATE,
    LINE_TOTAL_LKR,

    YEAR,
    MONTH,

    _HASH_DIFF
)

VALUES (

    src.TRANSACTION_ID,
    TRY_TO_DATE(src.TRANSACTION_DATE,'MM/DD/YYYY'),

    src.BRANCH_ID,
    UPPER(TRIM(src.BRANCH_NAME)),
    UPPER(TRIM(src.DISTRICT)),
    UPPER(TRIM(src.PROVINCE)),

    UPPER(TRIM(src.PAYMENT_METHOD)),

    UPPER(TRIM(src.CUSTOMER_GENDER)),
    src.CUSTOMER_AGE,
    UPPER(TRIM(src.CUSTOMER_CITY)),

    src.MEDICINE_ID,
    src.MEDICINE_NAME,
    src.GENERIC_NAME,
    src.MEDICINE_CATEGORY,
    src.DOSAGE_FORM,
    src.STRENGTH_MG,
    src.PACK_SIZE,

    src.SUPPLIER_NAME,

    CASE
        WHEN UPPER(src.PRESCRIPTION_REQUIRED)='YES'
        THEN TRUE
        ELSE FALSE
    END,

    src.BATCH_NO,
    TRY_TO_DATE(src.EXPIRY_DATE,'MM/DD/YYYY'),

    src.QUANTITY,
    src.UNIT_PRICE_LKR,
    src.DISCOUNT_RATE,
    src.LINE_TOTAL_LKR,

    src.YEAR,
    src.MONTH,

    src._HASH_DIFF
);

INSERT INTO KARTHICKY_DB."2_SILVER".REJECTED_RECORDS (TRANSACTION_ID, REJECT_REASON, RAW_DATA)

SELECT

    TRANSACTION_ID,

    CASE
        WHEN TRANSACTION_ID IS NULL
        THEN 'NULL_TRANSACTION_ID'

        WHEN TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY') IS NULL
        THEN 'INVALID_DATE'

        WHEN BRANCH_ID IS NULL
        THEN 'NULL_BRANCH_ID'

        WHEN TRIM(BRANCH_NAME) = '' OR BRANCH_NAME IS NULL
        THEN 'MISSING_BRANCH_NAME'

        WHEN TRIM(DISTRICT) = '' OR DISTRICT IS NULL
        THEN 'MISSING_DISTRICT'

        WHEN TRIM(PROVINCE) = '' OR PROVINCE IS NULL
        THEN 'MISSING_PROVINCE'

        WHEN UPPER(PAYMENT_METHOD) NOT IN ('CASH','CARD','INSURANCE')
        THEN 'INVALID_PAYMENT_METHOD'

        WHEN UPPER(CUSTOMER_GENDER) NOT IN ('MALE','FEMALE')
        THEN 'INVALID_GENDER'

        WHEN CUSTOMER_AGE IS NULL OR CUSTOMER_AGE < 0 OR CUSTOMER_AGE > 120
        THEN 'INVALID_CUSTOMER_AGE'

        WHEN TRIM(CUSTOMER_CITY) = '' OR CUSTOMER_CITY IS NULL
        THEN 'MISSING_CUSTOMER_CITY'

        WHEN MEDICINE_ID IS NULL
        THEN 'NULL_MEDICINE_ID'

        WHEN TRIM(MEDICINE_NAME) = '' OR MEDICINE_NAME IS NULL
        THEN 'MISSING_MEDICINE_NAME'

        WHEN UPPER(DOSAGE_FORM) NOT IN ('TABLET','CAPSULE','SYRUP','DROPS','CREAM','OINTMENT','INHALER','SACHET')
        THEN 'INVALID_DOSAGE_FORM'

        WHEN PACK_SIZE IS NULL OR PACK_SIZE <= 0
        THEN 'INVALID_PACK_SIZE'

        WHEN TRIM(SUPPLIER_NAME) = '' OR SUPPLIER_NAME IS NULL
        THEN 'MISSING_SUPPLIER_NAME'

        WHEN UPPER(PRESCRIPTION_REQUIRED) NOT IN ('YES','NO')
        THEN 'INVALID_PRESCRIPTION_REQUIRED'

        WHEN TRIM(BATCH_NO) = '' OR BATCH_NO IS NULL
        THEN 'MISSING_BATCH_NO'

        WHEN TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') IS NULL
        THEN 'INVALID_EXPIRY_DATE'

        WHEN TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') < TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY')
        THEN 'EXPIRY_BEFORE_TRANSACTION'

        WHEN QUANTITY IS NULL OR QUANTITY <= 0
        THEN 'INVALID_QUANTITY'

        WHEN UNIT_PRICE_LKR IS NULL OR UNIT_PRICE_LKR <= 0
        THEN 'INVALID_PRICE'

        WHEN DISCOUNT_RATE IS NULL OR DISCOUNT_RATE < 0 OR DISCOUNT_RATE > 1
        THEN 'INVALID_DISCOUNT_RATE'

        WHEN LINE_TOTAL_LKR IS NULL OR LINE_TOTAL_LKR <= 0
        THEN 'INVALID_LINE_TOTAL'

        WHEN YEAR IS NULL OR YEAR < 2000 OR YEAR > 2100
        THEN 'INVALID_YEAR'

        WHEN MONTH IS NULL OR MONTH < 1 OR MONTH > 12
        THEN 'INVALID_MONTH'

        ELSE 'UNKNOWN'
    END,

    OBJECT_CONSTRUCT(*)

FROM KARTHICKY_DB."2_SILVER".STG_BRONZE

WHERE _CDC_ACTION != 'DELETE'
AND (
    TRANSACTION_ID IS NULL
    OR TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY') IS NULL
    OR BRANCH_ID IS NULL
    OR TRIM(BRANCH_NAME) = '' OR BRANCH_NAME IS NULL
    OR TRIM(DISTRICT) = '' OR DISTRICT IS NULL
    OR TRIM(PROVINCE) = '' OR PROVINCE IS NULL
    OR UPPER(PAYMENT_METHOD) NOT IN ('CASH','CARD','INSURANCE')
    OR UPPER(CUSTOMER_GENDER) NOT IN ('MALE','FEMALE')
    OR CUSTOMER_AGE IS NULL OR CUSTOMER_AGE < 0 OR CUSTOMER_AGE > 120
    OR TRIM(CUSTOMER_CITY) = '' OR CUSTOMER_CITY IS NULL
    OR MEDICINE_ID IS NULL
    OR TRIM(MEDICINE_NAME) = '' OR MEDICINE_NAME IS NULL
    OR UPPER(DOSAGE_FORM) NOT IN ('TABLET','CAPSULE','SYRUP','DROPS','CREAM','OINTMENT','INHALER','SACHET')
    OR PACK_SIZE IS NULL OR PACK_SIZE <= 0
    OR TRIM(SUPPLIER_NAME) = '' OR SUPPLIER_NAME IS NULL
    OR UPPER(PRESCRIPTION_REQUIRED) NOT IN ('YES','NO')
    OR TRIM(BATCH_NO) = '' OR BATCH_NO IS NULL
    OR TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') IS NULL
    OR TRY_TO_DATE(EXPIRY_DATE,'MM/DD/YYYY') < TRY_TO_DATE(TRANSACTION_DATE,'MM/DD/YYYY')
    OR QUANTITY IS NULL OR QUANTITY <= 0
    OR UNIT_PRICE_LKR IS NULL OR UNIT_PRICE_LKR <= 0
    OR DISCOUNT_RATE IS NULL OR DISCOUNT_RATE < 0 OR DISCOUNT_RATE > 1
    OR LINE_TOTAL_LKR IS NULL OR LINE_TOTAL_LKR <= 0
    OR YEAR IS NULL OR YEAR < 2000 OR YEAR > 2100
    OR MONTH IS NULL OR MONTH < 1 OR MONTH > 12
);

v_rows_rejected := SQLROWCOUNT;

v_rows_processed := (SELECT COUNT(*) FROM KARTHICKY_DB."2_SILVER".STG_BRONZE WHERE _CDC_ACTION != 'DELETE');
v_rows_inserted := :v_rows_processed - :v_rows_rejected;

INSERT INTO KARTHICKY_DB."2_SILVER".PIPELINE_AUDIT_LOG
    (TASK_NAME, LAYER, ACTION, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_REJECTED, STATUS, BATCH_ID)
VALUES
    ('TASK_LOAD_SILVER', 'SILVER', 'MERGE', :v_rows_processed, :v_rows_inserted, 0, :v_rows_rejected, 'SUCCESS', :v_batch_id);

END;
